package jabs.network.stats.eightysixcountries;

public enum EightySixCountries {
    ALBANIA(0),
    ALGERIA(1),
    ARGENTINA(2),
    AUSTRALIA(3),
    AUSTRIA(4),
    BANGLADESH(5),
    BELGIUM(6),
    BRAZIL(7),
    BULGARIA(8),
    CAMBODIA(9),
    CANADA(10),
    CHILE(11),
    CHINA(12),
    COLOMBIA(13),
    COSTA_RICA(14),
    CROATIA(15),
    CYPRUS(16),
    CZECH_REPUBLIC(17),
    DENMARK(18),
    ESTONIA(19),
    FINLAND(20),
    FRANCE(21),
    GEORGIA(22),
    GERMANY(23),
    GHANA(24),
    GREECE(25),
    GUATEMALA(26),
    HONDURAS(27),
    HONG_KONG(28),
    HUNGARY(29),
    INDIA(30),
    INDONESIA(31),
    IRAN(32),
    IRELAND(33),
    ISRAEL(34),
    ITALY(35),
    JAPAN(36),
    KAZAKHSTAN(37),
    KENYA(38),
    KOSOVO(39),
    LATVIA(40),
    LEBANON(41),
    LITHUANIA(42),
    LUXEMBOURG(43),
    MALAYSIA(44),
    MALTA(45),
    MEXICO(46),
    MOLDOVA(47),
    MOROCCO(48),
    NETHERLANDS(49),
    NEW_ZEALAND(50),
    NIGERIA(51),
    NORWAY(52),
    PAKISTAN(53),
    PANAMA(54),
    PERU(55),
    PHILIPPINES(56),
    POLAND(57),
    PORTUGAL(58),
    ROMANIA(59),
    RUSSIA(60),
    SAUDI_ARABIA(61),
    SERBIA(62),
    SINGAPORE(63),
    SLOVAKIA(64),
    SLOVENIA(65),
    SOUTH_AFRICA(66),
    SOUTH_KOREA(67),
    SPAIN(68),
    SURINAME(69),
    SWEDEN(70),
    SWITZERLAND(71),
    TAIWAN(72),
    TANZANIA(73),
    THAILAND(74),
    TUNISIA(75),
    TURKEY(76),
    UGANDA(77),
    UKRAINE(78),
    UNITED_ARAB_EMIRATES(79),
    UNITED_KINGDOM(80),
    UNITED_STATES(81),
    URUGUAY(82),
    VENEZUELA(83),
    VIETNAM(84),
    WORLD(85);

    public static final EightySixCountries[] sixRegionsValues = EightySixCountries.values();

    private final int value;
    EightySixCountries(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
